### ISSUE TITLE
Implement Task Categorization Homescreen

### ISSUE THREAD

**Issue by JohnYangSam** [JohnYangSam/mwork-android#9]
Implement Task Categorization Homescreen

![screen shot 2014-11-20 at 9 06 59 pm](https://cloud.githubusercontent.com/assets/1061341/5179265/ae6976d8-742f-11e4-9c78-7eec5b8b85ff.png)

**Comment by allenyu0915** [comment]
Are we getting rid of the single session tasks? Also instead of "traveling" maybe we can use other words such as "active" or something else? Can somebody change the original image files?

**Comment by JohnYangSam** [comment]
@allenyu0915 - can you add a task to add the icon files to the Google Drive
(either @andreasy or @coligado should have them)

Active or traveling labels don't really matter for now, we can switch them
easily. Active probably makes the most sense.

On Wed, Nov 26, 2014 at 11:32 PM, allenyu0915 notifications@github.com
wrote:

> Are we getting rid of the single session tasks? Also instead of
> "traveling" maybe we can use other words such as "active" or something
> else? Can somebody change the original image files?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JohnYangSam/mwork-android/issues/9#issuecomment-64754950
> .

## 

Stanford CS | 650-681-7680
BASES http://bases.stanford.edu/ | SVI Hackspace
http://bases.stanford.edu/ | ACM http://stanfordacm.com/ | _Mi3_
Blog http://johnyangsam.com/ | @johnys http://www.twitter.com/johnys |
LinkedIn http://linkedin.com/in/johnys | Reading List
https://groups.google.com/forum/#!forum/john-ys-reading-list

**Comment by allenyu0915** [comment]
@JohnYangSam I think to replace single session we can put "current task" as one of them because right now we have no way of getting to a task after we "Save and exit"

**Comment by JohnYangSam** [comment]
Implemented
